### ISSUE TITLE
No match found for keyword "healingreceived"

### ISSUE THREAD

**Issue by cpbeaslin** [Zezombye/overpy#255] opened 2021-01-08 17:10 UTC
as the title says, the decompiler will error with healing received

**Comment by Zezombye** [comment] 2021-01-08 17:29
I can't reproduce it, can you give me the code with the error?

**Comment by cpbeaslin** [comment] 2021-01-08 18:19
https://github.com/cpbeaslin/OverStat/blob/main/workshop.txt

**Comment by Zezombye** [comment] 2021-01-09 22:29
Fixed in 6.7.2, thanks for reporting!

**Closed by Zezombye** 2021-01-09 22:29 UTC
